site_name: Women Football Data Platform
site_url: https://yvonnegitau.github.io/women-football-data-warehouse/
docs_dir: docs/

repo_name: 'yvonnegitau/women-football-data-warehouse'
repo_url: 'https://github.com/yvonnegitau/women-football-data-warehouse'

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - index.md
  - storage.md
  - extraction.md
  - orchestration.md
  - transformation_modelling.md
  - catalog.md
  - monitoring.md
